/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current system status with live values and controller state */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today's solar forecast (hourly) */
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current controller configuration */
        get: operations["getConfig"];
        /** Update controller configuration */
        put: operations["updateConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/controller/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch controller mode (auto/manual/winter) */
        post: operations["setControllerMode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/controller/setpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set manual grid setpoint (only in manual mode) */
        put: operations["setManualSetpoint"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verschattung/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Verschattung state (cover positions + states + engine inputs) */
        get: operations["getVerschattungState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verschattung/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision log (most recent first) */
        get: operations["getVerschattungDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verschattung/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVerschattungConfig"];
        put: operations["putVerschattungConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verschattung/cover/{id}/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putVerschattungCoverPosition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verschattung/cover/{id}/auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postVerschattungCoverAuto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        /** @enum {string} */
        ControllerMode: "auto" | "manual" | "winter";
        SystemStatus: {
            pv: {
                /** @description Current PV power in watts */
                power: number;
            };
            grid: {
                /** @description Current grid power in watts (negative = feed-in) */
                power: number;
                /** @description Current grid setpoint in watts */
                setpoint: number;
            };
            battery: {
                /** @description Battery power in watts (positive = charging) */
                power: number;
                /** @description State of charge in percent (0-100) */
                soc: number;
            };
            consumption: {
                /** @description Total consumption in watts */
                power: number;
            };
            controller: {
                mode: components["schemas"]["ControllerMode"];
                /** @description Currently active grid setpoint in watts */
                activeSetpoint: number;
                /** @description Human-readable reason for current setpoint */
                reason?: string;
            };
            /** Format: date-time */
            timestamp: string;
        };
        ControllerConfig: {
            batteryCapacityKwh: number;
            minSocPercent: number;
            targetSocPercent: number;
            maxAcPowerW: number;
            winterModeThresholdFactor: number;
            regulationIntervalMs: number;
            largeChangeThresholdW: number;
            deadbandW: number;
        };
        ForecastHour: {
            /** Format: date-time */
            timestamp: string;
            /** @description Forecasted power in watts for this hour */
            powerW: number;
        };
        ForecastResponse: {
            hours: components["schemas"]["ForecastHour"][];
            /** @description Total forecasted production for the day in kWh */
            totalKwh: number;
            /** @description Whether winter mode threshold is met */
            winterModeActive: boolean;
        };
        SetModeRequest: {
            mode: components["schemas"]["ControllerMode"];
        };
        SetSetpointRequest: {
            setpointW: number;
        };
        ErrorResponse: {
            error: string;
        };
        VerschattungStateResponse: {
            covers: components["schemas"]["VerschattungCoverState"][];
            inputs: components["schemas"]["VerschattungInputs"];
            rooms: components["schemas"]["VerschattungRoom"][];
        };
        VerschattungRoom: {
            id: string;
            /** @enum {string} */
            floor: "EG" | "OG";
            label: string;
            tempC: number | null;
            humidity: number | null;
        };
        VerschattungCoverState: {
            id: string;
            /** @enum {string} */
            zone: "ost" | "sued" | "west";
            /** @enum {string} */
            floor: "EG" | "OG";
            label: string;
            currentPosition: number | null;
            /** @enum {string} */
            state: "IDLE" | "CLOSED_BY_AUTO" | "OVERRIDE";
            expectedPosition: number | null;
            lastEvent?: {
                ts?: string;
                /** @enum {string} */
                source?: "auto" | "user" | "reset";
                fromPosition?: number | null;
                toPosition?: number | null;
                reason?: string | null;
            } | null;
        };
        VerschattungInputs: {
            sun: {
                azimuthDeg: number;
                elevationDeg: number;
            };
            pvPowerW: number | null;
            pvThresholdW: number;
            indoorTempC: number | null;
            isSummerMode: boolean;
        };
        VerschattungDecision: {
            coverId: string;
            /** @enum {string} */
            zone: "ost" | "sued" | "west";
            /** @enum {string} */
            action: "close" | "open" | "skip";
            reason: string;
            evaluatedConditions: {
                name: string;
                ok: boolean;
                detail: string;
            }[];
            appliedAt: string;
            /** @enum {string} */
            resultingState: "IDLE" | "CLOSED_BY_AUTO" | "OVERRIDE";
            expectedPosition?: number | null;
        };
        VerschattungConfig: {
            zones: {
                ost: components["schemas"]["VerschattungZoneTunables"];
                sued: components["schemas"]["VerschattungZoneTunables"];
                west: components["schemas"]["VerschattungZoneTunables"];
            };
            pvThreshold: {
                peakWp: number;
                factor: number;
                floorW: number;
            };
            indoorTempThresholdC: number;
            hysteresisIndoorTempC: number;
            hysteresisPvFactor: number;
            hysteresisPvDurationMinutes: number;
            summerModeMonths: number[];
        };
        VerschattungZoneTunables: {
            closePosition: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current system status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    getForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forecast data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControllerConfig"];
                };
            };
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControllerConfig"];
            };
        };
        responses: {
            /** @description Updated config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControllerConfig"];
                };
            };
        };
    };
    setControllerMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetModeRequest"];
            };
        };
        responses: {
            /** @description Mode updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    setManualSetpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSetpointRequest"];
            };
        };
        responses: {
            /** @description Setpoint updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            /** @description Not in manual mode */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVerschattungState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerschattungStateResponse"];
                };
            };
        };
    };
    getVerschattungDecisions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decision array */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerschattungDecision"][];
                };
            };
        };
    };
    getVerschattungConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerschattungConfig"];
                };
            };
        };
    };
    putVerschattungConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerschattungConfig"];
            };
        };
        responses: {
            /** @description Updated config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerschattungConfig"];
                };
            };
        };
    };
    putVerschattungCoverPosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    position: number;
                };
            };
        };
        responses: {
            /** @description Sent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postVerschattungCoverAuto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Override released */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
